# This is ordered and divided into modules .bashrc file.
# Check readme for more informations.
#
# Author: Michal Katnik (github.com/rideee).
#
# Source this file to your .bashrc or link it.


# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Bashrc modules directory path.
# Use absolute path because then is possible to make symbolic link to root's
# .bashrc, even if this file is store in $HOME directory.
BASHRC_MODULES="/home/rid/.aio-conf/bash/modules"

# Auto loader - use autoloader to manage auto loaded scripts.
# Run 'autoloader help' for more informations.
source "$BASHRC_MODULES/autoload.sh"

# General config - use vigeneral to edit this file.
source "$BASHRC_MODULES/general.sh"

# $PS1-GIT 
source "$BASHRC_MODULES/ps1-git.sh"

# Aliases - use vialiases to edit this file. 
# This file also import another file with private aliases,
# use viprivaliases to edit.
source "$BASHRC_MODULES/aliases.sh"

# Environment variables - use vienvs to edit this file.
source "$BASHRC_MODULES/env-vars.sh"
