# This is ordered and divided into modules .bashrc file.
# Check readme for more informations.
#
# Author: Michal Katnik (github.com/rideee).
# License: GPL.
#
# For manually connection use:
#   ln -s [this_file] ~/.bashrc

# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Bashrc modules directory path.
# Use absolute path because then is possible to make symbolic link to root's
# .bashrc, even if this file is store in $HOME directory.
BASHRC_MODULES="/home/rid/.aio-conf/bash/modules"

# Auto loader - use autoloader for manage auto loaded scripts.
# Run 'autoloader help' for more informations.
source "$BASHRC_MODULES/autoload.sh"

# General config - use vigeneral for editing this file.
source "$BASHRC_MODULES/general.sh"

# $PS1-GIT - For more informations use:
#   head -n 15 $BASHRC_MODULES/ps1-git.sh | tail -n 10
source "$BASHRC_MODULES/ps1-git.sh"

# Aliases - use vialiases for editing this file.
source "$BASHRC_MODULES/aliases.sh"

# Environment variables - use vienvs for editing this file.
source "$BASHRC_MODULES/env-vars.sh"

# Third-party.
#
# qfc (https://github.com/pindexis/qfc)
[[ -s "$BASHRC_MODULES/third-party/qfc/bin/qfc.sh" ]] \
  && source "$BASHRC_MODULES/third-party/qfc/bin/qfc.sh"

# HSTR (https://github.com/dvorka/hstr)
# Check github page for readme.
# Requires installation.
[ "$(type hstr 2>/dev/null)"  ] \
  && [[ -s "$BASHRC_MODULES/third-party/hstr/hstr.sh" ]] \
  && source "$BASHRC_MODULES/third-party/hstr/hstr.sh"

